---
- project:
    name: openstack-k8s-operators/test-operator
    github-check:
      jobs:
        - openstack-k8s-operators-content-provider:
            vars:
              cifmw_operator_build_meta_build: false
        - podified-multinode-edpm-deployment-crc-test-operator:
            dependencies:
              - openstack-k8s-operators-content-provider
            vars:
              cifmw_test_operator_index: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/test-operator-index:{{ zuul.patchset }}"
    periodic:
      jobs:
        - openstack-k8s-operators-content-provider:
            vars:
              cifmw_operator_build_meta_build: false
        - podified-multinode-edpm-deployment-crc-test-operator:
            dependencies:
              - openstack-k8s-operators-content-provider

- job:
    name: podified-multinode-edpm-deployment-crc-test-operator
    parent: podified-multinode-edpm-deployment-crc
    vars:
      cifmw_install_yamls_whitelisted_vars:
        - 'TEST_REPO'
        - 'TEST_BRANCH'
        - 'OUTPUT_DIR'

      cifmw_run_test_role: test_operator

      cifmw_run_tempest: true
      cifmw_test_operator_concurrency: 4
      cifmw_test_operator_timeout: 7200
      cifmw_test_operator_tempest_include_list: |
        ^tempest.
      cifmw_test_operator_tempest_exclude_list: |
        tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_migration_with_trunk
        tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate
        tempest.api.compute.servers.test_server_rescue.ServerStableDeviceRescueTestIDE
        tempest.api.compute.servers.test_device_tagging
        tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON
        tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario
        tempest.scenario.test_stamp_pattern
        tempest.scenario.test_network_advanced_server_ops.TestNetworkAdvancedServerOps.test_server_connectivity_live_migration
        tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_mtu_sized_frames
        test_create_server_invalid_bdm_in_2nd_dict
        tempest.api.identity.admin.v3.test_credentials.CredentialsTestJSON
        tempest.api.identity.admin.v3.test_tokens.TokensV3TestJSON.test_rescope_token
        tempest.api.identity.admin.v3.test_users.UsersV3TestJSON.test_update_user_password
      cifmw_tempest_tempestconf_config:
        overrides: |
          identity.v3_endpoint_type public
          service_available.swift false
          service_available.cinder false
      cifmw_test_operator_tempest_workflow:
        - stepName: 'full'
        - stepName: 'single-test'
          tempestRun:
            includeList: |
              tempest.api.compute.admin.test_flavors.FlavorsAdminTestJSON.test_create_flavor_using_string_ram
      cifmw_test_operator_tempest_extra_images:
        - URL: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
          name: cirros-0.6.2-test-operator
          flavor:
            name: cirros-0.6.2-test-operator-flavor
            RAM: 512
            disk: 20
            vcpus: 1
      cifmw_test_operator_tempest_ntp_extra_images: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
      cifmw_test_operator_tempest_network_attachments:
        - ctlplane

      cifmw_run_tobiko: true
      cifmw_test_operator_tobiko_workflow:
        - stepName: 'podified-functional'
          testenv: 'functional -- tobiko/tests/functional/podified/test_topology.py'
          numProcesses: 2
        - stepName: 'sanity'
          testenv: 'sanity'
      cifmw_test_operator_tobiko_network_attachments:
        - ctlplane
    required-projects: &rp
      - name: openstack-k8s-operators/install_yamls
        override-checkout: main
      - name: openstack-k8s-operators/openstack-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/ci-framework
        override-checkout: main
      - name: github.com/openstack-k8s-operators/repo-setup
        override-checkout: main
      - name: github.com/openstack-k8s-operators/infra-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-baremetal-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/edpm-ansible
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-must-gather
        override-checkout: main
