---
- project:
    name: openstack-k8s-operators/test-operator
    github-check:
      jobs:
        - openstack-k8s-operators-content-provider:
            vars:
              cifmw_operator_build_meta_build: false
        - podified-multinode-edpm-deployment-crc-test-operator:
            dependencies:
              - openstack-k8s-operators-content-provider
            vars:
              cifmw_test_operator_bundle: "{{ content_provider_registry_ip }}:5001/openstack-k8s-operators/test-operator:{{ zuul.patchset }}"
              cifmw_test_operator_version: "{{ zuul.patchset }}"
    periodic:
      jobs:
        - openstack-k8s-operators-content-provider:
            vars:
              cifmw_operator_build_meta_build: false
        - podified-multinode-edpm-deployment-crc-test-operator:
            dependencies:
              - openstack-k8s-operators-content-provider

- job:
    name: podified-multinode-edpm-deployment-crc-test-operator
    parent: podified-multinode-hci-deployment-crc-1comp-backends
    vars:
      cifmw_install_yamls_whitelisted_vars:
        - 'TEST_REPO'
        - 'TEST_BRANCH'
        - 'OUTPUT_DIR'

      cifmw_run_test_role: test_operator

      # Test operator
      cifmw_test_operator_timeout: 7200
      cifmw_test_operator_stages:
        - name: tempest
          type: tempest
        - name: tobiko
          type: tobiko
        - name: ansibletest
          type: ansibletest
        - name: horizontest
          type: horizontest

      # Tempest
      cifmw_run_tempest: true
      cifmw_test_operator_tempest_concurrency: 4
      cifmw_test_operator_tempest_cleanup: true
      cifmw_test_operator_tempest_include_list: |
        ^tempest.
      cifmw_test_operator_tempest_exclude_list: |
        # Note (lpiwowar): Unskip test_verify_hostname_allows_fqdn once the
        #                  Details: Timeout while verifying metadata on server
        #                  error is resolved.
        tempest.api.compute.servers.test_create_server.ServersV294TestFqdnHostnames.test_verify_hostname_allows_fqdn
        tempest.api.compute.admin.test_live_migration.LiveMigrationTest.test_live_migration_with_trunk
        tempest.api.compute.admin.test_auto_allocate_network.AutoAllocateNetworkTest.test_server_multi_create_auto_allocate
        tempest.api.compute.servers.test_server_rescue.ServerStableDeviceRescueTestIDE
        tempest.api.compute.servers.test_device_tagging
        tempest.api.network.admin.test_dhcp_agent_scheduler.DHCPAgentSchedulersTestJSON
        tempest.scenario.test_minimum_basic.TestMinimumBasicScenario.test_minimum_basic_scenario
        tempest.scenario.test_stamp_pattern
        tempest.scenario.test_network_advanced_server_ops.TestNetworkAdvancedServerOps.test_server_connectivity_live_migration
        tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_mtu_sized_frames
        test_create_server_invalid_bdm_in_2nd_dict
        tempest.api.identity.admin.v3.test_credentials.CredentialsTestJSON
        tempest.api.identity.admin.v3.test_tokens.TokensV3TestJSON.test_rescope_token
        tempest.api.identity.admin.v3.test_users.UsersV3TestJSON.test_update_user_password
      cifmw_test_operator_tempest_expected_failures_list: |
        foobar
      cifmw_test_operator_tempest_tempestconf_config:
        overrides: |
          compute-feature-enabled.dhcp_domain ''
          dashboard.dashboard_url https://horizon-openstack.apps-crc.testing/dashboard/
          dashboard.login_url https://horizon-openstack.apps-crc.testing/dashboard/auth/login/
          dashboard.disable_ssl_certificate_validation True
          identity.v3_endpoint_type public
          service_available.swift false
          service_available.cinder false
          service_available.horizon True
      cifmw_test_operator_tempest_workflow:
        - stepName: 'full'
        - stepName: 'single-test'
          tempestRun:
            includeList: |
              tempest.api.compute.admin.test_flavors.FlavorsAdminTestJSON.test_create_flavor_using_string_ram
            concurrency: 8
          tempestconfRun:
            collectTiming: true

      cifmw_test_operator_tempest_extra_images:
        - URL: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
          name: cirros-0.6.2-test-operator
          imageCreationTimeout: 300
          flavor:
            name: cirros-0.6.2-test-operator-flavor
            RAM: 512
            disk: 20
            vcpus: 1
      cifmw_test_operator_tempest_ntp_extra_images: https://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
      cifmw_test_operator_tempest_network_attachments:
        - ctlplane
      cifmw_test_operator_tempest_extra_mounts:
        - name: v1
          region: r1
          extraVol:
            - propagation:
              - Tempest
              extraVolType: Ceph
              volumes:
              - name: ceph
                secret:
                  secretName: openstack-config-secret
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true

      # Tobiko
      cifmw_run_tobiko: true
      cifmw_test_operator_tobiko_workflow:
        - stepName: 'podified-functional'
          testenv: 'functional -- tobiko/tests/functional/podified/test_topology.py'
          numProcesses: 2
        - stepName: 'sanity'
          testenv: 'sanity'
      cifmw_test_operator_tobiko_network_attachments:
        - ctlplane
      cifmw_test_operator_tobiko_extra_mounts:
        - name: v1
          region: r1
          extraVol:
            - propagation:
              - Tobiko
              extraVolType: Ceph
              volumes:
              - name: ceph
                secret:
                  secretName: openstack-config-secret
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true

      # Horizontest
      cifmw_run_horizontest: true
      cifmw_test_operator_horizontest_auth_url: "https://keystone-public-openstack.apps-crc.testing"
      cifmw_test_operator_horizontest_dashboard_url: "https://horizon-openstack.apps-crc.testing/"
      cifmw_test_operator_horizontest_extra_flag: "not pagination and test_users.py"
      cifmw_test_operator_horizontest_project_name_xpath: //*[@class="context-project"]//ancestor::ul
      cifmw_test_operator_horizontest_extra_mounts:
        - name: v1
          region: r1
          extraVol:
            - propagation:
              - HorizonTest
              extraVolType: Ceph
              volumes:
              - name: ceph
                secret:
                  secretName: openstack-config-secret
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true

      # Ansibletest
      run_ansibletest: true
      cifmw_test_operator_ansibletest_ansible_git_repo: https://github.com/ansible/test-playbooks
      cifmw_test_operator_ansibletest_ansible_playbook_path: ./debug.yml
      cifmw_test_operator_ansibletest_workload_ssh_key_secret_name: test-operator-controller-priv-key
      cifmw_test_operator_ansibletest_ansible_extra_vars: -e manual_run=false
      cifmw_test_operator_ansibletest_ansible_inventory: |
        localhost ansible_connection=local ansible_python_interpreter=python3
      cifmw_test_operator_ansibletest_ansible_var_files: |
        ---
        foo: bar
      cifmw_test_operator_ansibletest_extra_mounts:
        - name: v1
          region: r1
          extraVol:
            - propagation:
              - AnsibleTest
              extraVolType: Ceph
              volumes:
              - name: ceph
                secret:
                  secretName: openstack-config-secret
              mounts:
              - name: ceph
                mountPath: "/etc/ceph"
                readOnly: true

      pre_deploy:
        - name: 61 HCI pre deploy kustomizations
          type: playbook
          source: control_plane_hci_pre_deploy.yml
        - name: 80 Kustomize OpenStack CR
          type: playbook
          source: control_plane_horizon.yml


    required-projects: &rp
      - name: openstack-k8s-operators/install_yamls
        override-checkout: main
      - name: openstack-k8s-operators/openstack-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/ci-framework
        override-checkout: main
      - name: github.com/openstack-k8s-operators/repo-setup
        override-checkout: main
      - name: github.com/openstack-k8s-operators/infra-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-baremetal-operator
        override-checkout: main
      - name: github.com/openstack-k8s-operators/edpm-ansible
        override-checkout: main
      - name: github.com/openstack-k8s-operators/openstack-must-gather
        override-checkout: main
