apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../bases/tempest
patches:
- patch: |-
    - op: replace
      path: /metadata/namespace
      value: test-operator-kuttl-tests
  target:
    kind: Tempest
