# permissions for end users to view horizons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: horizon-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: test-operator
    app.kubernetes.io/part-of: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: horizon-viewer-role
rules:
- apiGroups:
  - test.openstack.org
  resources:
  - horizons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.openstack.org
  resources:
  - horizons/status
  verbs:
  - get
