apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: openstack
  name: test-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Tempest is the Schema for the tempests API
      displayName: Tempest
      kind: Tempest
      name: tempests.test.openstack.org
      specDescriptors:
      - description: BackoffLimimt allows to define the maximum number of retried
          executions (defaults to 6).
        displayName: Backoff Limit
        path: backoffLimit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: BackoffLimimt allows to define the maximum number of retried
          executions (defaults to 6).
        displayName: Backoff Limit
        path: workflow[0].backoffLimit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      version: v1beta1
    - description: Tobiko is the Schema for the tobikoes API
      displayName: Tobiko
      kind: Tobiko
      name: tobikos.test.openstack.org
      specDescriptors:
      - description: BackoffLimimt allows to define the maximum number of retried
          executions (defaults to 6).
        displayName: Backoff Limit
        path: backoffLimit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Name of a secret that contains a kubeconfig. The kubeconfig is
          mounted under /var/lib/tobiko/.kube/config in the test pod.
        displayName: Kubeconfig Secret Name
        path: kubeconfigSecretName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: A parameter  that contains a workflow definition.
        displayName: Workflow
        path: workflow
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: BackoffLimimt allows to define the maximum number of retried
          executions (defaults to 6).
        displayName: Backoff Limit
        path: workflow[0].backoffLimit
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: Name of a secret that contains a kubeconfig. The kubeconfig is
          mounted under /var/lib/tobiko/.kube/config in the test pod.
        displayName: Kubeconfig Secret Name
        path: workflow[0].kubeconfigSecretName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: A parameter that contains a definition of a single workflow step.
        displayName: Step Name
        path: workflow[0].stepName
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      version: v1beta1
  description: Test Operator
  displayName: OpenStack Test Operator
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - OpenStack
  - Tempest
  links:
  - name: Test Operator
    url: https://github.com/openstack-k8s-operators/test-operator
  maturity: beta
  provider:
    name: Red Hat Inc.
    url: https://redhat.com/
  version: 0.0.0
