## Append samples of your project ##
resources:
- test_v1beta1_tempest.yaml
- test_v1beta1_tobiko.yaml
- test_v1beta1_horizontest.yaml
- test_v1beta1_ansibletest.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
