apiVersion: test.openstack.org/v1beta1
kind: Tobiko
metadata:
  labels:
    app.kubernetes.io/name: test-operator
    app.kubernetes.io/managed-by: kustomize
  name: tobiko-sample
spec:
  # TODO(user): Add fields here
