---
apiVersion: test.openstack.org/v1beta1
kind: Tobiko
metadata:
  name: tobiko-tests
  namespace: openstack
spec:
  containerImage: quay.io/podified-antelope-centos9/openstack-tobiko:current-podified
  # storageClass: local-storage
  # parallel: false
  # privateKey: |
  #   <private-key-value>
  # publicKey: |
  #   <public-key-value>
  # numProcesses: <integer>
  # preventCreate: <true/false>
  # pytestAddopts: >- # example:
  #   -m <markers>
  #   --maxfail <max-failed-tests>
  #   --skipregex <regex>
  testenv: py3
  version: master
  config: |
    [DEFAULT]
    log_file = value

    [testcase]
    timeout = value
    test_runner_timeout = value

    [ubuntu]
    interface_name = value

    [keystone]
    interface_name = value
