---
apiVersion: test.openstack.org/v1beta1
kind: Tobiko
metadata:
  name: tobiko-tests
  namespace: openstack
spec:
  containerImage: ""

  # Privileged
  # ----------
  #
  # Use with caution! This parameter specifies whether test-operator should spawn test
  # pods with allowedPrivilegedEscalation: true and the default capabilities on
  # top of capabilities that are usually needed by the test pods (NET_ADMIN, NET_RAW).
  # This parameter is deemed insecure but it is needed for certain test-operator
  # functionalities to work properly (e.g.: extraRPMs in Tempest CR, or certain set
  # of tobiko tests).
  #
  # privileged: false

  # storageClass: local-storage
  # parallel: false
  # debug: false
  # privateKey: |
  #   <private-key-value>
  # publicKey: |
  #   <public-key-value>
  # numProcesses: <integer>
  # preventCreate: <true/false>
  # pytestAddopts: >- # example:
  #   -m <markers>
  #   --maxfail <max-failed-tests>
  #   --skipregex <regex>
  testenv: py3
  version: master
  config: |
    [DEFAULT]
    log_file = value

    [testcase]
    timeout = value
    test_runner_timeout = value

    [ubuntu]
    interface_name = value

    [keystone]
    interface_name = value
  workflow:
    - stepName: unit-tests
      testenv: py3

    - stepName: functional-tests
      testenv: functional
