/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group test --version v1beta1 --kind HorizonTest --programmatic-validation --defaulting
//

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// log is for logging in this package.
var horizontestlog = logf.Log.WithName("horizontest-resource")

var _ webhook.Defaulter = &HorizonTest{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *HorizonTest) Default() {
	horizontestlog.Info("default", "name", r.Name)

	// TODO(user): fill in your defaulting logic.
}

var _ webhook.Validator = &HorizonTest{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *HorizonTest) ValidateCreate() (admission.Warnings, error) {
	horizontestlog.Info("validate create", "name", r.Name)

	var allWarnings admission.Warnings

	allWarnings = CheckPrivilegedWarning(allWarnings, r.Spec.Privileged, r.Kind)
	allWarnings = CheckExtraConfigmapsDeprecation(allWarnings, r.Spec.ExtraConfigmapsMounts)

	return allWarnings, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *HorizonTest) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	horizontestlog.Info("validate update", "name", r.Name)

	// TODO(user): fill in your validation logic upon object update.
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *HorizonTest) ValidateDelete() (admission.Warnings, error) {
	horizontestlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
