/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

//
// Generated by:
//
// operator-sdk create webhook --group test --version v1beta1 --kind Tempest --programmatic-validation --defaulting
//

package v1beta1

import (
	"errors"
	"fmt"

	"github.com/google/go-cmp/cmp"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/util/validation/field"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"
)

// log is for logging in this package.
var tempestlog = logf.Log.WithName("tempest-resource")

var _ webhook.Defaulter = &Tempest{}

// Default implements webhook.Defaulter so a webhook will be registered for the type
func (r *Tempest) Default() {
	tempestlog.Info("default", "name", r.Name)

	r.Spec.Default()
}

// Default - set defaults for this Tempest spec.
func (spec *TempestSpec) Default() {
	if spec.ContainerImage == "" {
		spec.ContainerImage = testDefaults.TempestContainerImageURL
	}

	if spec.TempestconfRun == (TempestconfRunSpec{}) {
		spec.TempestconfRun.Create = true
	}
}

func (r *Tempest) PrivilegedRequired() bool {
	return len(r.Spec.TempestRun.ExtraImages) > 0
}

var _ webhook.Validator = &Tempest{}

// ValidateCreate implements webhook.Validator so a webhook will be registered for the type
func (r *Tempest) ValidateCreate() (admission.Warnings, error) {
	tempestlog.Info("validate create", "name", r.Name)

	var allErrs field.ErrorList
	var allWarnings admission.Warnings

	// Common validations
	allErrs = ValidatePodName(allErrs, r.Name, r.Kind)
	allWarnings = CheckPrivilegedWarning(allWarnings, r.Spec.Privileged, r.Kind)
	allWarnings = CheckExtraConfigmapsDeprecation(allWarnings, r.Spec.ExtraConfigmapsMounts)

	// Workflow-specific validations
	if len(r.Spec.Workflow) > 0 {
		allErrs = ValidateDebugWorkflow(allErrs, r.Spec.Debug, r.Kind)
		allErrs = ValidateWorkflowPodNames(allErrs, r.Name, r.Kind, r.Spec.Workflow)
		allWarnings = CheckSELinuxWarning(allWarnings, r.Spec.Privileged, r.Spec.SELinuxLevel, r.Kind)
		allWarnings = CheckWorkflowExtraConfigmapsDeprecation(allWarnings, r.Spec.Workflow)
	}

	// Privileged mode validation
	if !r.Spec.Privileged && r.PrivilegedRequired() {
		allErrs = append(allErrs, &field.Error{
			Type:     field.ErrorTypeRequired,
			BadValue: r.Spec.Privileged,
			Detail:   fmt.Sprintf(ErrPrivilegedModeRequired, r.Kind),
		})
	}

	if err := BuildValidationError(r.Kind, r.GetName(), allErrs); err != nil {
		return allWarnings, err
	}

	return allWarnings, nil
}

// ValidateUpdate implements webhook.Validator so a webhook will be registered for the type
func (r *Tempest) ValidateUpdate(old runtime.Object) (admission.Warnings, error) {
	tempestlog.Info("validate update", "name", r.Name)

	oldTempest, ok := old.(*Tempest)
	if !ok || oldTempest == nil {
		return nil, errors.New("unable to convert existing object")
	}

	if !cmp.Equal(oldTempest.Spec, r.Spec) {
		warnings := admission.Warnings{}
		warnings = append(warnings, "You are updating an already existing instance of a "+
			"Tempest CR! Be aware that changes won't be applied.")

		return warnings, errors.New("updating an existing Tempest CR is not supported")
	}
	return nil, nil
}

// ValidateDelete implements webhook.Validator so a webhook will be registered for the type
func (r *Tempest) ValidateDelete() (admission.Warnings, error) {
	tempestlog.Info("validate delete", "name", r.Name)

	// TODO(user): fill in your validation logic upon object deletion.
	return nil, nil
}
