name: Build documentation and deploy it to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - docs/** # Trigger only when changes are made inside docs/
  pull_request:
    paths:
      - docs/** # Trigger only when changes are made inside docs/
  workflow_dispatch:
    paths:
      - docs/** # Trigger manually for docs/

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ./docs/requirements.txt
      - name: Build documentation
        run: |
          TEMP_VENV_ENV="$(mktemp -d)"
          DOCS_DIR="./docs"
          python -m venv ${TEMP_VENV_ENV} && source ${TEMP_VENV_ENV}/bin/activate
          pip install -c ${UPPER_CONSTRAINTS_FILE:-https://releases.openstack.org/constraints/upper/master} -r ${DOCS_DIR}/requirements.txt
          doc8 --config ${DOCS_DIR}/doc8.ini ${DOCS_DIR}/source
          sphinx-build -a -E -W -d ${DOCS_DIR}/build/doctrees --keep-going -b html ${DOCS_DIR}/source ./docs_build/html -T
          deactivate
          rm -fr ${TEMP_VENV_ENV}
      - name: Upload artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: ./docs_build/html
